cmsapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'cmsapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^:(?P<tag>[^/]+)/$', views.index, name='index'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', views.page, name='page'),
    url(r'^\+$', views.change, name='change'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/edit$', views.change, name='change'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/delete$', views.delete, name='delete'),
]

cmsproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^cms/', include("cmsapp.urls", namespace="cms")),
    url(r'^todo/', include("todoapp.urls", namespace="todo")),
]

todoapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'todoapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<list_id>[0-9]+)/add$', views.add, name='add'),
    url(r'^(?P<list_id>[0-9]+)/$', views.todos, name='todos'),
    url(r'^(?P<list_id>[0-9]+)/delete$', views.delete, name='delete'),

]

cmsapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from binascii import hexlify
from os import urandom


def make_default_slug():
    return hexlify(urandom(16))


# Create your models here.

class Page(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    slug = models.SlugField(max_length=200, unique=True, default=make_default_slug)

    def __repr__(self):  # https://pyformat.info/
        return "<Page #{0.pk} slug={0.slug!r} title={0.title!r}" \
               " content={0.content!r:.5}>".format(self)  # pragma: no cover


class Tag(models.Model):
    name = models.CharField(max_length=200)
    page = models.ForeignKey("Page", on_delete=models.CASCADE,related_name='tags',
                             related_query_name='tag')

todoapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.


class ListToDo(models.Model):
    name = models.CharField(max_length=200)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name + " " + str(self.date.strftime("%Y-%m-%d %H:%M:%S")) # pragma: no cover


class ToDo(models.Model):
    description = models.CharField(max_length=200)
    list = models.ForeignKey("ListToDo", on_delete=models.CASCADE)

    def __str__(self):
        return '"{}"'.format(self.description) # pragma: no cover

cmsapp/forms.py
from django import forms

from .models import Page, Tag


class TagField(forms.CharField):
    def clean(self, value):
        value = super(TagField, self).clean(value)
        tags = [item.strip() for item in value.split(",")]
        return [tag for tag in tags if tag]


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = "title", "content"

    tags = TagField(required=False)

    def __init__(self, data=None, initial=None, instance=None, **kwargs):
        if instance:
            initial = initial or {}
            initial['tags'] = ', '.join(instance.tags.values_list('name',flat=True))
        return super(PageForm, self).__init__(data, initial=initial, instance=instance,
                                              **kwargs)

    def save(self, commit=True): # pragma: no cover
        instance = super(PageForm, self).save(commit)
        if commit:
            self.instance.tags.all().delete()
            Tag.objects.bulk_create([
                Tag(name=tag, page=self.instance)
                for tag in self.cleaned_data['tags']])
        return instance

todoapp/forms.py
from django import forms

from .models import ToDo

class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = "description",

cmsapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.

from .models import Page, Tag
from .forms import PageForm


def index(request, tag=None):
    if tag is None:
        pages = Page.objects.all()
    else:
        pages = Page.objects.filter(tag__name=tag)
    return render(request, "cmsapp/index.html", {
        'pages': pages,
        'tags': Tag.objects.values('name').distinct(),
    })


def page(request, slug):
    page = get_object_or_404(Page, slug=slug)
    return render(request, "cmsapp/page.html",
                  {'page':page,
                   'tags':page.tags.all()})


def change(request, slug=None):
    if slug is None:
        instance = None
    else:
        instance = get_object_or_404(Page, slug=slug)
    if request.method == "POST":
        form = PageForm(request.POST, instance=instance)
        if form.is_valid():
            instance = form.save()
            return redirect("cmsapp:page", slug=instance.slug)
    else:
        form = PageForm(instance=instance)
    return render(request, "cmsapp/change.html", {
        'form': form, 'page': instance})

@login_required
def delete(request, slug):
    if request.method == "POST":
        instance = get_object_or_404(Page, slug=slug)
        instance.delete()
        return redirect("cmsapp:index")
    else:
        return redirect("cmsapp:page", slug=slug)

todoapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.utils.datastructures import MultiValueDictKeyError

from .models import ListToDo, ToDo
from .forms import ToDoForm

# Create your views here.

def index(request):
    lists = ListToDo.objects.all()
    return render(request, "todoapp/index.html", {"lists": lists})


def todos(request, list_id):
    list = get_object_or_404(ListToDo, pk=list_id)
    todos = ToDo.objects.filter(list=list)
    return render(request, "todoapp/todos.html", {"list": list, "todos": todos})


def add(request, list_id):
    list = get_object_or_404(ListToDo, pk=list_id)
    if request.method == 'POST':
        form = ToDoForm(request.POST)
        if form.is_valid():
            ToDo.objects.create(description=form.cleaned_data["description"], list=list)
            return redirect("todoapp:todos", list_id=list.id)
    else:
        form = ToDoForm()
    return render(request, "todoapp/add.html", {'form': form, 'list': list})


def delete(request, list_id):
    if request.method == "POST":
        try:
            todo = get_object_or_404(ToDo, pk=request.POST["todo_id"])
            todo.delete()
        except MultiValueDictKeyError:
            print("select a todo")
        finally:
            return redirect("todoapp:todos", list_id=list_id)
    else:
        return redirect("todoapp:index")

cmsapp/templates/cmsapp/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}No title{% endblock %}</title>
    <h1>{% block h1%}{% endblock %}</h1>
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

cmsapp/templates/cmsapp/change.html
{% extends "cmsapp/base.html" %}
{% block title %}
    {% if page %}
        {{ page.title }} [editing]
    {% else %}
        [adding new page]
    {% endif %}
{% endblock %}
{% block body%}
    <form method="post" action="{% spaceless %}
          {% if page %}
              {% url 'cmsapp:change' page.slug %}
          {% else %}
              {% url 'cmsapp:change' %}
          {% endif %}{% endspaceless %}">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <button type="submit">Save</button>
    </form>
{% endblock %}

cmsapp/templates/cmsapp/includes/tags.html
{% if tags %}
<p>By tag:
    {% for tag in tags %}
    <a href="{% url 'cmsapp:index' tag.name %}">
        {{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
{% endif %}

cmsapp/templates/cmsapp/index.html
{% extends "cmsapp/base.html" %}
{% block title %} Pages {% endblock %}
{% block h1 %} Pages {% endblock %}
{% block body %}

{% include "cmsapp/includes/tags.html" %}

<ul>
    {% for page in pages %}
    <li><a href="{% url 'cmsapp:page' page.slug %}">{{page.title}}</a></li>
    {% empty %}
    No pages yet!
    {% endfor %}
</ul>

<a href="{% url 'cmsapp:change' %}">Add page</a>

{% endblock %}

cmsapp/templates/cmsapp/page.html
{% extends "cmsapp/base.html" %}
{% block title%} {{ page.title }} {% endblock %}
{% block h1%} {{ page.title }} {% endblock %}
{% block body %}
{% include "cmsapp/includes/tags.html" %}
<a href="{% url 'cmsapp:change' page.slug %}"> {{ page.content }} </a><br>
<form action="{% url 'cmsapp:delete' page.slug %}" method="post">
    {% csrf_token %}
     <button type="submit">Delete</button>
</form>
{% endblock %}

todoapp/templates/todoapp/add.html
{% extends "todoapp/base.html" %}
{% block title %} Add {% endblock %}
{% block h1 %} New ToDo {% endblock %}

{% block body %}
<form action="{% url 'todoapp:add' list.id%}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>
</form>
{% endblock %}

todoapp/templates/todoapp/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}No title{% endblock %}</title>
    <h1>{% block h1%}{% endblock %}</h1>
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

todoapp/templates/todoapp/index.html
{% extends "todoapp/base.html" %}
{% block title %} ToDo Lists {% endblock %}
{% block h1 %} My ToDo Lists: {% endblock %}

{% block body%}
<ul type="none">
    {% for list in lists %}
    <li> <a href="{% url 'todoapp:todos' list.id %}">{{list}} </a> </li>
    {% empty %}
    I don't have any lists!
    {% endfor %}
</ul>
{% endblock %}

todoapp/templates/todoapp/todos.html
{% extends "todoapp/base.html" %}
{% block title %} ToDos {% endblock %}
{% block h1 %} {{list.name}} todos: {% endblock %}

{% block body%}
<form action="{% url 'todoapp:delete' list.id%}" method="post">
    {% csrf_token %}
    <ul type="none">
        {% for todo in todos %}
        <li> <input type="radio" name="todo_id" value="{{todo.id}}"> {{todo}} </li>
        {% empty %}
        I don't have anything to do!
        {% endfor %}
    </ul>
     <button type="submit">Delete</button>
</form>
<br>
<a href="{% url 'todoapp:add' list.id%}">Add ToDo</a>
<br>
<h2><a href="{% url 'todoapp:index' %}">Home</a></h2>
{% endblock %}